### ISSUE TITLE
Error when using as described

### ISSUE THREAD

**Issue by mac10688** [iantocristian/kraken-devtools-browserify#6]
I'm using io.js on windows platform.
When I installed krakenjs it ran fine out of the box. 
I followed the directions in the readme and ran 

npm install --save-dev kraken-devtools-browserify

I ran the application again and it said

Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (F:\Programming\Projects\Nodejs\TestProject_Kraken_Bro
wserify\node_modules\kraken-devtools-browserify\node_modules\browserify\node_mod
ules\module-deps\node_modules\stream-combiner2\node_modules\through2\node_module
s\readable-stream\lib_stream_duplex.js:39:12)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (F:\Programming\Projects\Nodejs\TestProject_Kraken_Bro
wserify\node_modules\kraken-devtools-browserify\node_modules\browserify\node_mod
ules\module-deps\node_modules\stream-combiner2\node_modules\through2\node_module
s\readable-stream\lib_stream_duplex.js:39:12)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)

When I loaded the index page.

I ran npm install --save core-util-is

When I ran the website again with "npm start" I got a new message

Error: Cannot find module './source-map/source-map-generator'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (F:\Programming\Projects\Nodejs\TestProject_Kraken_Bro
wserify\node_modules\kraken-devtools-browserify\node_modules\browserify\node_mod
ules\browser-pack\node_modules\combine-source-map\node_modules\inline-source-map
\node_modules\source-map\lib\source-map.js:6:30)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
Error: Cannot find module './source-map/source-map-generator'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (F:\Programming\Projects\Nodejs\TestProject_Kraken_Bro
wserify\node_modules\kraken-devtools-browserify\node_modules\browserify\node_mod
ules\browser-pack\node_modules\combine-source-map\node_modules\inline-source-map
\node_modules\source-map\lib\source-map.js:6:30)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)

So I ran npm install --save source-map

But the error message still shows.

I went to that file specified and it shows 

/*
- Copyright 2009-2011 Mozilla Foundation and contributors
- Licensed under the New BSD license. See LICENSE.txt or:
- http://opensource.org/licenses/BSD-3-Clause
  */
  exports.SourceMapGenerator = require('./source-map/source-map-generator').SourceMapGenerator;
  exports.SourceMapConsumer = require('./source-map/source-map-consumer').SourceMapConsumer;
  exports.SourceNode = require('./source-map/source-node').SourceNode;

Here is a screenshot if it helps.
![image](https://cloud.githubusercontent.com/assets/2703261/7975345/ff47000e-0a32-11e5-8b34-ca09f4a1d42e.png)

**Comment by mac10688** [comment]
I just looked and all the files in that source-map folder are empty.

![image](https://cloud.githubusercontent.com/assets/2703261/7975363/2fa0f7a0-0a33-11e5-986b-fe3904a202df.png)

**Comment by mac10688** [comment]
Hope I'm not spamming but when I right click and opened containing folder and it took me somewhere strange. I did a character count on that path and it's 258 characters. I think windows only allows 255 characters in a path.

**Comment by mac10688** [comment]
Yeah, the filepath was too long :( Freaking windows!
